name: "testing-calendar"
services:
  database:
    image: postgres:17-alpine3.22
    container_name: testing-calendar-db
    restart: unless-stopped
    volumes:
      - testing-calendar-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${STORAGE_DATABASE_DBNAME}
      - POSTGRES_USER=${STORAGE_DATABASE_USER}
      - POSTGRES_PASSWORD=${STORAGE_DATABASE_PASS}
    ports:
      - ${STORAGE_DATABASE_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${STORAGE_DATABASE_USER} -d ${STORAGE_DATABASE_DBNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: testing-calendar-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672" # Management UI
      - ${BROKER_PORT}:5672   # AMQP port
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 60s
      retries: 5

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.26.0
    container_name: testing-calendar-migrations
    depends_on:
      database:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=postgres
      - GOOSE_DBSTRING=host=${STORAGE_DATABASE_HOST} port=${STORAGE_DATABASE_PORT} user=${STORAGE_DATABASE_USER} password=${STORAGE_DATABASE_PASS} dbname=${STORAGE_DATABASE_DBNAME}
    networks:
      - testing-calendar-network
    volumes:
      - ./../migrations:/migrations

  server:
    container_name: testing-calendar-server
    restart: unless-stopped
    build:
      context: ./../
      dockerfile: ./build/calendar.Dockerfile
    expose:
      - 80
    ports:
      - "80:80"
    depends_on:
      database:
        condition: service_healthy
        required: true
      migrations:
        condition: service_completed_successfully
        required: true
    environment:
      SERVER_HOST: "server"
      SERVER_PORT: 80

      LOGGER_FILE: "logs/app.log"

      STORAGE_DATABASE_HOST: ${STORAGE_DATABASE_HOST}
      STORAGE_DATABASE_PORT: ${STORAGE_DATABASE_PORT}
      STORAGE_DATABASE_DBNAME: ${STORAGE_DATABASE_DBNAME}
      STORAGE_DATABASE_USER: ${STORAGE_DATABASE_USER}
      STORAGE_DATABASE_PASS: ${STORAGE_DATABASE_PASS}
    volumes:
      - type: bind
        source: ./../logs/app
        target: /logs/testing
    networks:
      - testing-calendar-network

  sender:
    container_name: testing-calendar-sender
    restart: unless-stopped
    build:
      context: ./../
      dockerfile: ./build/sender.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
        required: true
    environment:
      LOGGER_FILE: "logs/sender.log"

      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      BROKER_USER: ${BROKER_USER}
    volumes:
      - type: bind
        source: ./../logs/sender
        target: /logs/testing
    networks:
      - testing-calendar-network

  scheduler:
    container_name: testing-calendar-scheduler
    restart: unless-stopped
    build:
      context: ./../
      dockerfile: ./build/scheduler.Dockerfile
    depends_on:
      rabbitmq:
        condition: service_healthy
        required: true
      database:
        condition: service_healthy
        required: true
      migrations:
        condition: service_completed_successfully
        required: true
    environment:
      LOGGER_FILE: "logs/scheduler.log"

      STORAGE_DATABASE_HOST: ${STORAGE_DATABASE_HOST}
      STORAGE_DATABASE_PORT: ${STORAGE_DATABASE_PORT}
      STORAGE_DATABASE_DBNAME: ${STORAGE_DATABASE_DBNAME}
      STORAGE_DATABASE_USER: ${STORAGE_DATABASE_USER}
      STORAGE_DATABASE_PASS: ${STORAGE_DATABASE_PASS}

      BROKER_HOST: ${BROKER_HOST}
      BROKER_PORT: ${BROKER_PORT}
      BROKER_PASSWORD: ${BROKER_PASSWORD}
      BROKER_USER: ${BROKER_USER}
    volumes:
      - type: bind
        source: ./../logs/scheduler
        target: /logs/testing
    networks:
      - testing-calendar-network

  # Контейнер с интеграционными тестами
  integration-tests:
    container_name: integration-tests
    profiles:
      - tests
    build:
      context: ./../
      dockerfile: ./build/integration.Dockerfile
    environment:
      API_URL: http://server:80
      DATABASE_DSN: postgres://${STORAGE_DATABASE_USER}:${STORAGE_DATABASE_PASS}@${STORAGE_DATABASE_HOST}:${STORAGE_DATABASE_PORT}/${STORAGE_DATABASE_DBNAME}?sslmode=disable
    depends_on:
      server:
        condition: service_started
        required: true
      scheduler:
        condition: service_started
        required: true
      sender:
        condition: service_started
        required: true
    networks:
      - testing-calendar-network

volumes:
  testing-calendar-db-data:
    name: testing-calendar-db-data
  rabbitmq-data:
    name: testing-calendar-rabbitmq-data
networks:
  testing-calendar-network:
    driver: bridge