server:
  type: "http" #grpc|http
  host: "localhost"
  port: 80
logger:
  level: "INFO"
  file: "logs/app.log"
storage:
  type: "database" #in-memory|database
  database:
    host: "localhost"
    port: 5432
    dbname: "calendar"
    user: "calendar_app"
    pass: "app_calendar"
    conn:
      lifetime: 5 #minutes
      max_open: 25
      max_idle: 25