// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: EventService.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcedureResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcedureResult) Reset() {
	*x = ProcedureResult{}
	mi := &file_EventService_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcedureResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureResult) ProtoMessage() {}

func (x *ProcedureResult) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureResult.ProtoReflect.Descriptor instead.
func (*ProcedureResult) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{0}
}

func (x *ProcedureResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ProcedureResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	StartTime     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	Desc          string                 `protobuf:"bytes,5,opt,name=desc,proto3" json:"desc,omitempty"`
	OwnerId       string                 `protobuf:"bytes,6,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	NotifyTime    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=notify_time,json=notifyTime,proto3" json:"notify_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_EventService_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Event) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Event) GetEndTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EndTime
	}
	return nil
}

func (x *Event) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *Event) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Event) GetNotifyTime() *timestamppb.Timestamp {
	if x != nil {
		return x.NotifyTime
	}
	return nil
}

type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_EventService_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventRequest) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_EventService_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{3}
}

func (x *CreateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	UpdatedEvent  *Event                 `protobuf:"bytes,2,opt,name=updated_event,json=updatedEvent,proto3" json:"updated_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_EventService_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *UpdateEventRequest) GetUpdatedEvent() *Event {
	if x != nil {
		return x.UpdatedEvent
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_EventService_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_EventService_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteEventRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type DeleteEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_EventService_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{7}
}

type GetEventsForDayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=day,proto3" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsForDayRequest) Reset() {
	*x = GetEventsForDayRequest{}
	mi := &file_EventService_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsForDayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsForDayRequest) ProtoMessage() {}

func (x *GetEventsForDayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsForDayRequest.ProtoReflect.Descriptor instead.
func (*GetEventsForDayRequest) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{8}
}

func (x *GetEventsForDayRequest) GetDay() *timestamppb.Timestamp {
	if x != nil {
		return x.Day
	}
	return nil
}

type GetEventsForDayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsForDayResponse) Reset() {
	*x = GetEventsForDayResponse{}
	mi := &file_EventService_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsForDayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsForDayResponse) ProtoMessage() {}

func (x *GetEventsForDayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsForDayResponse.ProtoReflect.Descriptor instead.
func (*GetEventsForDayResponse) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{9}
}

func (x *GetEventsForDayResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventsForWeekRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartOfWeek   *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_of_week,json=startOfWeek,proto3" json:"start_of_week,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsForWeekRequest) Reset() {
	*x = GetEventsForWeekRequest{}
	mi := &file_EventService_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsForWeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsForWeekRequest) ProtoMessage() {}

func (x *GetEventsForWeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsForWeekRequest.ProtoReflect.Descriptor instead.
func (*GetEventsForWeekRequest) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{10}
}

func (x *GetEventsForWeekRequest) GetStartOfWeek() *timestamppb.Timestamp {
	if x != nil {
		return x.StartOfWeek
	}
	return nil
}

type GetEventsForWeekResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsForWeekResponse) Reset() {
	*x = GetEventsForWeekResponse{}
	mi := &file_EventService_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsForWeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsForWeekResponse) ProtoMessage() {}

func (x *GetEventsForWeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsForWeekResponse.ProtoReflect.Descriptor instead.
func (*GetEventsForWeekResponse) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{11}
}

func (x *GetEventsForWeekResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type GetEventsForMonthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartOfMonth  *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start_of_month,json=startOfMonth,proto3" json:"start_of_month,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsForMonthRequest) Reset() {
	*x = GetEventsForMonthRequest{}
	mi := &file_EventService_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsForMonthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsForMonthRequest) ProtoMessage() {}

func (x *GetEventsForMonthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsForMonthRequest.ProtoReflect.Descriptor instead.
func (*GetEventsForMonthRequest) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{12}
}

func (x *GetEventsForMonthRequest) GetStartOfMonth() *timestamppb.Timestamp {
	if x != nil {
		return x.StartOfMonth
	}
	return nil
}

type GetEventsForMonthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventsForMonthResponse) Reset() {
	*x = GetEventsForMonthResponse{}
	mi := &file_EventService_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventsForMonthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventsForMonthResponse) ProtoMessage() {}

func (x *GetEventsForMonthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_EventService_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventsForMonthResponse.ProtoReflect.Descriptor instead.
func (*GetEventsForMonthResponse) Descriptor() ([]byte, []int) {
	return file_EventService_proto_rawDescGZIP(), []int{13}
}

func (x *GetEventsForMonthResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_EventService_proto protoreflect.FileDescriptor

const file_EventService_proto_rawDesc = "" +
	"\n" +
	"\x12EventService.proto\x12\bcalendar\x1a\x1fgoogle/protobuf/timestamp.proto\"A\n" +
	"\x0fProcedureResult\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x8b\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x129\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x125\n" +
	"\bend_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aendTime\x12\x12\n" +
	"\x04desc\x18\x05 \x01(\tR\x04desc\x12\x19\n" +
	"\bowner_id\x18\x06 \x01(\tR\aownerId\x12;\n" +
	"\vnotify_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"notifyTime\";\n" +
	"\x12CreateEventRequest\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05event\"<\n" +
	"\x13CreateEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05event\"e\n" +
	"\x12UpdateEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x124\n" +
	"\rupdated_event\x18\x02 \x01(\v2\x0f.calendar.EventR\fupdatedEvent\"<\n" +
	"\x13UpdateEventResponse\x12%\n" +
	"\x05event\x18\x01 \x01(\v2\x0f.calendar.EventR\x05event\"/\n" +
	"\x12DeleteEventRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"\x15\n" +
	"\x13DeleteEventResponse\"F\n" +
	"\x16GetEventsForDayRequest\x12,\n" +
	"\x03day\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x03day\"B\n" +
	"\x17GetEventsForDayResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\"Y\n" +
	"\x17GetEventsForWeekRequest\x12>\n" +
	"\rstart_of_week\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\vstartOfWeek\"C\n" +
	"\x18GetEventsForWeekResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events\"\\\n" +
	"\x18GetEventsForMonthRequest\x12@\n" +
	"\x0estart_of_month\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\fstartOfMonth\"D\n" +
	"\x19GetEventsForMonthResponse\x12'\n" +
	"\x06events\x18\x01 \x03(\v2\x0f.calendar.EventR\x06events2\x8b\x04\n" +
	"\bCalendar\x12L\n" +
	"\vCreateEvent\x12\x1c.calendar.CreateEventRequest\x1a\x1d.calendar.CreateEventResponse\"\x00\x12L\n" +
	"\vUpdateEvent\x12\x1c.calendar.UpdateEventRequest\x1a\x1d.calendar.UpdateEventResponse\"\x00\x12L\n" +
	"\vDeleteEvent\x12\x1c.calendar.DeleteEventRequest\x1a\x1d.calendar.DeleteEventResponse\"\x00\x12X\n" +
	"\x0fGetEventsForDay\x12 .calendar.GetEventsForDayRequest\x1a!.calendar.GetEventsForDayResponse\"\x00\x12[\n" +
	"\x10GetEventsForWeek\x12!.calendar.GetEventsForWeekRequest\x1a\".calendar.GetEventsForWeekResponse\"\x00\x12^\n" +
	"\x11GetEventsForMonth\x12\".calendar.GetEventsForMonthRequest\x1a#.calendar.GetEventsForMonthResponse\"\x00B\aZ\x05./;pbb\x06proto3"

var (
	file_EventService_proto_rawDescOnce sync.Once
	file_EventService_proto_rawDescData []byte
)

func file_EventService_proto_rawDescGZIP() []byte {
	file_EventService_proto_rawDescOnce.Do(func() {
		file_EventService_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_EventService_proto_rawDesc), len(file_EventService_proto_rawDesc)))
	})
	return file_EventService_proto_rawDescData
}

var file_EventService_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_EventService_proto_goTypes = []any{
	(*ProcedureResult)(nil),           // 0: calendar.ProcedureResult
	(*Event)(nil),                     // 1: calendar.Event
	(*CreateEventRequest)(nil),        // 2: calendar.CreateEventRequest
	(*CreateEventResponse)(nil),       // 3: calendar.CreateEventResponse
	(*UpdateEventRequest)(nil),        // 4: calendar.UpdateEventRequest
	(*UpdateEventResponse)(nil),       // 5: calendar.UpdateEventResponse
	(*DeleteEventRequest)(nil),        // 6: calendar.DeleteEventRequest
	(*DeleteEventResponse)(nil),       // 7: calendar.DeleteEventResponse
	(*GetEventsForDayRequest)(nil),    // 8: calendar.GetEventsForDayRequest
	(*GetEventsForDayResponse)(nil),   // 9: calendar.GetEventsForDayResponse
	(*GetEventsForWeekRequest)(nil),   // 10: calendar.GetEventsForWeekRequest
	(*GetEventsForWeekResponse)(nil),  // 11: calendar.GetEventsForWeekResponse
	(*GetEventsForMonthRequest)(nil),  // 12: calendar.GetEventsForMonthRequest
	(*GetEventsForMonthResponse)(nil), // 13: calendar.GetEventsForMonthResponse
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_EventService_proto_depIdxs = []int32{
	14, // 0: calendar.Event.start_time:type_name -> google.protobuf.Timestamp
	14, // 1: calendar.Event.end_time:type_name -> google.protobuf.Timestamp
	14, // 2: calendar.Event.notify_time:type_name -> google.protobuf.Timestamp
	1,  // 3: calendar.CreateEventRequest.event:type_name -> calendar.Event
	1,  // 4: calendar.CreateEventResponse.event:type_name -> calendar.Event
	1,  // 5: calendar.UpdateEventRequest.updated_event:type_name -> calendar.Event
	1,  // 6: calendar.UpdateEventResponse.event:type_name -> calendar.Event
	14, // 7: calendar.GetEventsForDayRequest.day:type_name -> google.protobuf.Timestamp
	1,  // 8: calendar.GetEventsForDayResponse.events:type_name -> calendar.Event
	14, // 9: calendar.GetEventsForWeekRequest.start_of_week:type_name -> google.protobuf.Timestamp
	1,  // 10: calendar.GetEventsForWeekResponse.events:type_name -> calendar.Event
	14, // 11: calendar.GetEventsForMonthRequest.start_of_month:type_name -> google.protobuf.Timestamp
	1,  // 12: calendar.GetEventsForMonthResponse.events:type_name -> calendar.Event
	2,  // 13: calendar.Calendar.CreateEvent:input_type -> calendar.CreateEventRequest
	4,  // 14: calendar.Calendar.UpdateEvent:input_type -> calendar.UpdateEventRequest
	6,  // 15: calendar.Calendar.DeleteEvent:input_type -> calendar.DeleteEventRequest
	8,  // 16: calendar.Calendar.GetEventsForDay:input_type -> calendar.GetEventsForDayRequest
	10, // 17: calendar.Calendar.GetEventsForWeek:input_type -> calendar.GetEventsForWeekRequest
	12, // 18: calendar.Calendar.GetEventsForMonth:input_type -> calendar.GetEventsForMonthRequest
	3,  // 19: calendar.Calendar.CreateEvent:output_type -> calendar.CreateEventResponse
	5,  // 20: calendar.Calendar.UpdateEvent:output_type -> calendar.UpdateEventResponse
	7,  // 21: calendar.Calendar.DeleteEvent:output_type -> calendar.DeleteEventResponse
	9,  // 22: calendar.Calendar.GetEventsForDay:output_type -> calendar.GetEventsForDayResponse
	11, // 23: calendar.Calendar.GetEventsForWeek:output_type -> calendar.GetEventsForWeekResponse
	13, // 24: calendar.Calendar.GetEventsForMonth:output_type -> calendar.GetEventsForMonthResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_EventService_proto_init() }
func file_EventService_proto_init() {
	if File_EventService_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_EventService_proto_rawDesc), len(file_EventService_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_EventService_proto_goTypes,
		DependencyIndexes: file_EventService_proto_depIdxs,
		MessageInfos:      file_EventService_proto_msgTypes,
	}.Build()
	File_EventService_proto = out.File
	file_EventService_proto_goTypes = nil
	file_EventService_proto_depIdxs = nil
}
